recruiter-app/main/default/objects/JobAdvServiceCredentials__c/JobAdvServiceCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>JobAdvServiceCredentials</label>
</CustomObject>

recruiter-app/main/default/objects/JobAdvServiceCredentials__c/fields/BaseUri__c.field-meta.xml
<CustomField>
    <fullName>BaseUri__c</fullName>
    <label>BaseUri</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

recruiter-app/main/default/objects/JobAdvServiceCredentials__c/fields/Grant__c.field-meta.xml
<CustomField>
    <fullName>Grant__c</fullName>
    <label>GrantType</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

recruiter-app/main/default/objects/JobAdvServiceCredentials__c/fields/SecurityToken__c.field-meta.xml
<CustomField>
    <fullName>SecurityToken__c</fullName>
    <label>SecurityToken</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

recruiter-app/main/default/classes/core/callouts/JobAdvWebToken.cls
public class JobAdvWebToken implements IwebToken {
    public static final Integer STATUS_CODE_OK = 200;

    public WebToken getToken(){
        JobAdvServiceCredentials__c settings = JobAdvServiceCredentials__c.getInstance();
        HttpRequest request = new HttpRequest();
        request.setMethod(HttpConstants.METHOD_POST);
        request.setEndpoint(settings.BaseUri__c);
        request.setBody('grant_type='+settings.Grant__c 
                        + '&client_id='+settings.ClientId__c 
                        + '&client_secret='+settings.ClientSecret__c 
                        + '&username='+settings.Username__c 
                        + '&password='+settings.Password__c + settings.SecurityToken__c); 
        HttpResponse response= new Http().send(request);
        if(response.getStatusCode()!=STATUS_CODE_OK){
            throw new WebTokenException(response.getBody());
        }       
        WebToken token = new Webtoken();       
        try{
            token = (WebToken) JSON.deserialize(response.getBody(), WebToken.class);
        }
        catch(JsonException exc){
            throw new WebTokenException(exc.getMessage(),exc);
        }      
        return token;       
    }
}