recruiter-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

recruiter-app/main/default/objects/Candidate__c/fields/PhotoFileId__c.field-meta.xml
<CustomField>
    <fullName>PhotoFileId__c</fullName>
    <label>PhotoFileId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

recruiter-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

recruiter-app/main/default/objects/Job_Application__c/fields/PositionCandidateKey__c.field-meta.xml
<CustomField>
    <fullName>PositionCandidateKey__c</fullName>
    <externalId>true</externalId>
    <label>PositionCandidateKey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

recruiter-app/main/default/objects/Position__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

recruiter-app/main/default/classes/core/services/JobAppServiceImpl.cls
public class JobAppServiceImpl implements IjobAppService {
    private IfileService fileService;


    public JobAppServiceImpl(IfileService fileService){
        this.fileService = fileService;

    }
    
    public void updateJobAppByExternalResumeDTO(List<ResumeDTO> resumeDtoList){
        ResumeDTOContainer container = new ResumeDTOContainer(resumeDtoList);
        Savepoint savePoint = Database.setSavepoint();
        try{
            List<Position__c> positionsWithExternalIdOnly =  container.getPositionsOnlyWithExternalId();
            fillPositionActualIdByExternalId(positionsWithExternalIdOnly);
            List<Candidate__c> candidates = container.getCandidates();
            upsert candidates Email__c;
            List<FileDetails> fileDetailsList = container.getFileDetailsList();
            fileService.removeFilesByContentVersionIds(extractContentVersionIdsFromCandidates(candidates));
            fileService.saveFiles(fileDetailsList);
            fillPhotoFileIds(candidates, fileDetailsList);
            update candidates;
            List<Job_Application__c> jobApps = container.getJobApps();
            upsert jobApps PositionCandidateKey__c;
        }
        catch(DmlException dmlExc){
            Database.rollback(savePoint);
            throw new JobAppServiceException(dmlExc.getMessage(), dmlExc);
        }
        catch(ClearFileException cfExc){
            Database.rollback(savePoint);
            throw new JobAppServiceException(cfExc.getMessage(), cfExc);
        }
        catch(SaveFileException sfExc){
            Database.rollback(savePoint);
            throw new JobAppServiceException(sfExc.getMessage(), sfExc);
        }

    }

    private void fillPositionActualIdByExternalId(List<Position__c> positionsWithExternalIdOnly){
         List<Position__c> actulPositions = 
         [SELECT ExternalId__c FROM Position__c WHERE ExternalId__c IN :extractPositionExternalIds(positionsWithExternalIdOnly)];
         fillPositionIds(positionsWithExternalIdOnly, actulPositions);
    }

    private void fillPositionIds(List<Position__c> externalPositions, List<Position__c> actualPositions){
        for(Position__c externalPosition:externalPositions){
            for(Position__c actualPosition:actualPositions){
                if(externalPosition.ExternalId__c==actualPosition.ExternalId__c){
                    externalPosition.id = actualPosition.id;
                }
            }
        }
    }

    private List<String> extractPositionExternalIds(List<Position__c> positionsWithExternalIdOnly){
        List<String> ids = new List<String>();
        for(Position__c position:positionsWithExternalIdOnly){
           ids.add(position.ExternalId__c);
        }
        return ids;
    }

    private List<Id> extractContentVersionIdsFromCandidates(List<Candidate__c> candidates){
        Map<Id, Candidate__c> candidateMap = new Map<Id,Candidate__c>(candidates);
        List<Candidate__c> retrievedCandidates = [SELECT PhotoFileId__c FROM Candidate__c WHERE id IN :candidateMap.keySet()];
        List<Id> contentVersionIds = new List<Id>();
        for (Candidate__c candidate:retrievedCandidates){
            contentVersionIds.add(candidate.PhotoFileId__c);
        }
        return contentVersionIds;

    }

    private void fillPhotoFileIds(List<Candidate__c> candidates, List<FileDetails> fileDetailsList){
       Map<Id, Candidate__c> candidateMap = new Map<Id,Candidate__c>(candidates);
       for(FileDetails fileDetails:fileDetailsList){
           candidateMap.get(fileDetails.relatedEntityId).PhotoFileId__c = fileDetails.contentVersionId;
       } 

    }
}